### ISSUE TITLE
求解答

### ISSUE THREAD

**Issue by bass808** [21wang12/zzu_jksb#1]
![Snipaste_2021-07-22_00-05-33](https://user-images.githubusercontent.com/80774667/126521893-87a8c321-3ed0-4677-95c9-26aea429142c.png)
这是为什么

**Comment by 21wang12** [comment]
程序运行到这里有两个原因：
1. 你当天登录次数太多了，引发了郑州大学服务器的防止DDoS机制，导致登陆时需要输入验证码。
2. 账号或者密码输入错误了。

对于第1种情况，你当天需要手动打卡才行，第二天就会恢复正常。

对于第2种情况，请检查账户名和密码是否正确
